
lpos = [
    'additional information',
 'additional voting matters',
 'agenda item',
 'annual meeting information',
 'audit committee report',
 'audit matters',
 'awards granted',
 'beneficial owners',
 'beneficial ownership',
 'board and committee matters',
 'board committee',
 'ceo pay ratio',
 'code of ethics',
 'compensation discussion & analysis',
 'compensation discussion and analysis',
 'compensation tables',
 'corporate governance guidelinespension benefits',
 'director and executive officer ownership',
 'director compensation',
 'director stock ownership requirement',
 'equity compensation',
 'equity incentive',
 'executive compensation table',
 'executive officer and director stock ownership',
 'five percent holders',
 'greater than 5% security holders',
 'holders of stock',
 'management ownership',
 'option exercises and stock vested',
 'outstanding equity awards',
 'ownership by directors',
 'ownership of certain beneficial owners',
 'ownership of equity securities',
 'ownership of principal stockholders',
 'ownership of voting securities',
 'plan benefits',
 'principal holders of stock',
 'principal shareholders',
 'principal stockholders',
 'proxy summary',
 'proxy statement',
 'related-party transactions',
 'relationships and related party transactions',
 'report of the hrc committee',
 'role of the compensation committee',
 'security ownership',
 'shareholder proposals ',
 'significant shareholders',
 'stock owned by directors',
 'stock ownership',
 'stock ownership guidelines',
 'stock ownership policy',
 'stockholder approval',
 'summary compensation table',
 'table of content'
        ]
lneg = [
 'cumulative',
 '$',
 'rsu',
 'name',
 'number',
 'gaap',


]